codecov:
  notify:
    after_n_builds: 1

coverage:
  precision: 3
  round: down
  range: 80...100

  status:
    project: true
    patch: off
    changes:
      default:
        threshold: 10%

comment: false